name: 'open issue reminder'

on:
  schedule:
    - cron: '30 5 * * *'  # This schedules the job to run at 10:00 PM UTC which is 4:30 AM IST
  issues:
    types: [assigned]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const issue of issues) {
              const issueComment = `
                This is an automated message to remind you about this issue. 
                Please provide any updates if needed.
              
                Assignees: ${issue.assignees.map(assignee => '@' + assignee.login).join(', ') || 'None'}
              `; // Tags all assignees or states "None" if there are no assignees

              await github.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: issueComment
              });
            }
