name: Check Open Issues

on:
  schedule:
    - cron: '20 16 * * *' # Run every day at 9 PM IST

jobs:
  check-open-issues:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Fetch open issues
        run: |
          python "https://github.com/RishitaChourey/CodeBites_PS_2.1.1/blob/main/.github/workflows/fetch_open_issues.py"
