name: Comment on Issues 

on:
  schedule:
    - cron: '45 5 * * *'

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `
             @${{ github.actor }}
               Hi there! This issue is still open. We are looking forward to your response.`
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            for (const issue of issues) {
              github.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: issueComment
              })
            }
