name: Comment on Issues

on:
  schedule:
    - cron: '03 6 * * *'

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            for (const issue of issues) {
              if (issue.assignees.length > 0) {
                const assignees = issue.assignees.map(assignee => `@${assignee.login}`).join(' ');
                const issueComment = `
                ${assignees}
                Hi there! This issue is still open. We are looking forward to your response.`;

                await github.issues.createComment({
                  issue_number: issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: issueComment
                });
              }
            }
