name: 'Reminder'

on:
  issues:
  issue_comment:
    types: [ created ]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message:
            'Hey, @${{ github.actor }}! This issue is still open.We are looking forward for your response.'
            
